/**
 * Render the seed dataset as SQL, so it can be applied through any Postgres
 * client. `npm run seed` remains the normal path; this exists for when the
 * service-role key is not available locally.
 *
 * Usage: node scripts/emitSql.js [maxTxnsPerMerchant] > seed.sql
 */
import { writeFileSync } from 'node:fs';
import { buildDataset, WIPE_ORDER, summarise } from './seed.js';

const MAX_TXNS = Number(process.argv[2] ?? 3);

const q = (v) => {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'object') return `'${JSON.stringify(v).replaceAll("'", "''")}'::jsonb`;
  return `'${String(v).replaceAll("'", "''")}'`;
};

function insert(table, rows) {
  if (!rows.length) return '';
  const cols = Object.keys(rows[0]);
  const values = rows
    .map((r) => `  (${cols.map((c) => q(r[c])).join(', ')})`)
    .join(',\n');
  return `INSERT INTO ${table} (${cols.join(', ')}) VALUES\n${values};\n`;
}

const data = buildDataset();

// Transactions are display-only on the case detail screen; a few per merchant
// is enough and keeps the generated file small.
const byMerchant = new Map();
const transactions = data.transactions.filter((t) => {
  const n = byMerchant.get(t.merchant_id) ?? 0;
  if (n >= MAX_TXNS) return false;
  byMerchant.set(t.merchant_id, n + 1);
  return true;
});

const sql = [
  '-- generated by scripts/emitSql.js',
  ...WIPE_ORDER.map((t) => `DELETE FROM ${t};`),
  '',
  insert('merchants', data.merchants),
  insert('merchant_flags', data.flags),
  insert('transactions', transactions),
  insert('settlements', data.settlements),
].join('\n');

writeFileSync('seed.sql', sql);
summarise({ ...data, transactions });
console.log(`\nseed.sql written (${(sql.length / 1024).toFixed(1)} KB, ${transactions.length} transactions kept)`);
